(ns geschichte.git-object-test
  (:require #?(:clj [clojure.test :refer [deftest is testing]]
               :cljs [cljs.test :refer-macros [deftest is testing]])
            [geschichte.bytes :as bytes]
            [geschichte.git.object :as object]))

(deftest canonical-blob-identities
  (is (= "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"
         (object/object-id :blob (bytes/empty-bytes))))
  (is (= "ce013625030ba8dba906f756967f9e9ca394464a"
         (object/object-id :blob (object/utf8 "hello\n"))))
  (is (= 64 (count (object/object-id :sha256 :blob (bytes/empty-bytes))))))

(deftest canonical-tree-and-commit-encoding
  (let [blob-oid (object/object-id :blob (object/utf8 "hello\n"))
        tree (object/tree-payload [{:mode "100644" :name "hello.txt"
                                    :oid blob-oid}])
        tree-oid (object/object-id :tree tree)
        commit (object/commit-payload
                {:tree tree-oid
                 :author "A U Thor <a@example.com> 0 +0000"
                 :committer "A U Thor <a@example.com> 0 +0000"
                 :message "initial\n"})]
    (testing "known values generated by native Git"
      (is (= "aaa96ced2d9a1c8e72c56b253a0e2fe78393feb7" tree-oid))
      (is (= "6dcdbcc7ef823bdc25845df5af9ac3f9b4712cb8"
             (object/object-id :commit commit))))))

(deftest rejects-invalid-tree-paths
  (is (thrown? #?(:clj clojure.lang.ExceptionInfo :cljs cljs.core.ExceptionInfo)
               (object/tree-payload [{:mode "100644" :name "a/b"
                                      :oid (apply str (repeat 40 "0"))}]))))

(deftest canonical-objects-parse-back-to-structure
  (let [blob-oid (object/object-id :blob (object/utf8 "hello\n"))
        tree-bytes (object/tree-payload
                    [{:mode "100644" :name "hello.txt" :oid blob-oid}])
        commit-bytes
        (object/commit-payload
         {:tree (object/object-id :tree tree-bytes)
          :parents [(apply str (repeat 40 "a"))]
          :author "Ada <ada@example.com> 1 +0000"
          :committer "Ada <ada@example.com> 2 +0000"
          :message "message\n"})
        tree (object/parse-tree tree-bytes)
        commit (object/parse-commit commit-bytes)]
    (is (= [{:mode "100644" :name "hello.txt" :oid blob-oid}]
           (mapv #(dissoc % :name-bytes) tree)))
    (is (= [(apply str (repeat 40 "a"))] (:parents commit)))
    (is (= "message\n" (:message commit)))
    (is (= "Ada <ada@example.com> 1 +0000" (:author commit))))
  (let [tag-bytes
        (object/tag-payload
         {:object (apply str (repeat 40 "b")) :type :commit :tag "v1"
          :tagger "Ada <ada@example.com> 3 +0000" :message "release\n"})]
    (is (= {:object (apply str (repeat 40 "b"))
            :type :commit :tag "v1" :message "release\n"}
           (select-keys (object/parse-tag tag-bytes)
                        [:object :type :tag :message])))))
